version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 741979147734.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t mooglelabs .
      - docker tag mooglelabs:latest 741979147734.dkr.ecr.us-east-1.amazonaws.com/mooglelabs:latest
      - docker push 741979147734.dkr.ecr.us-east-1.amazonaws.com/mooglelabs:latest
  post_build:
    commands:
      - aws eks --region us-east-1 update-kubeconfig  --name terraform-eks-demo
      - kubectl apply -f SampleApp.yaml
artifacts:
  files:
    - SampleApp.yaml
